### ISSUE TITLE
Location of AUPR implementation code

### ISSUE THREAD

**Issue by y-z-x** [CVIU-CSU/M2MRF-Lesion-Segmentation#11]
Dear author

I want to know the specific implementation code of AUPR, but I'm a bit confused about it。thank you。

**Comment by haotianll** [comment]
Hi, please check the code [here](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/mmseg/core/evaluation/my_metrics.py#L136) for the implementation of AUPR.
