### ISSUE TITLE
数据预处理出错

### ISSUE THREAD

**Issue by WHloveHZN** [CVIU-CSU/M2MRF-Lesion-Segmentation#12]
在对IDRID数据集进行预处理时，生成的标签是全黑色的，并未集合四种病变的标注信息。而对DDR数据集的预处理却成功了。这是什么原因导致的那，希望作者大大回复一下

**Comment by wk19990213** [comment]
![image](https://github.com/user-attachments/assets/214bc748-6ec6-4c77-915b-e2221fe2e82b)
你好，你的显卡显存是多少了，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢

**Comment by WHloveHZN** [comment]
你这个应该是内存不够导致的，建议释放一些内存
