### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by WHloveHZN** [CVIU-CSU/M2MRF-Lesion-Segmentation#13]
Hello, could you please tell me how to change the batch size?

**Comment by haotianll** [comment]
Hi, you can adjust the batch size per GPU [here](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/configs/_base_/datasets/idrid.py#L51).

**Comment by WHloveHZN** [comment]
Thanks for your assistance

**Comment by wk19990213** [comment]
![image](https://github.com/user-attachments/assets/2345c716-536c-49a9-9d77-5019b6f86f94)
你好，你的显卡显存是多少了，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢
