### ISSUE TITLE
Qualitative results

### ISSUE THREAD

**Issue by dkg123456** [CVIU-CSU/M2MRF-Lesion-Segmentation#14]
Dear author
I want to know how to generate qualitative results,and I passed the parameters in the terminal without generating qualitative results.thank you。

running command：CUDA_VISIBLE_DEVICES=0 PORT=12345 tools/dist_test.sh configs/m2mrf/fcn_hr48-M2MRF-C_40k_idrid_bdice.py ./work_dirs/fcn_hr48-M2MRF-C_40k_idrid_bdice/iter_40000.pth 1 --eval mIoU --show-dir results/

![b65f39fda9daaec768531675b16514e](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/146306195/38891dc8-1211-4360-a1bc-418b9aaa0ad9)

**Comment by haotianll** [comment]
Hi, did you use [prepare_labels.py](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/tools/prepare_labels.py) to prepare the dataset?

**Comment by dkg123456** [comment]
yes,sir

**Comment by haotianll** [comment]
Hi, Could you please share with me your email?

**Comment by dkg123456** [comment]
447934660@qq.com

**Comment by wk19990213** [comment]
![image](https://github.com/user-attachments/assets/1ab67f70-4ba0-40b2-aa07-69c2b6a48406)
你好，你的显卡显存是多少了，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢
