### ISSUE TITLE
visualized results

### ISSUE THREAD

**Issue by WHloveHZN** [CVIU-CSU/M2MRF-Lesion-Segmentation#15]
Hello, how can I save the visualized segmentation results into a specified folder? I apologize for my poor coding skills.

**Comment by haotianll** [comment]
Hi, you can check the `output_path` [here](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/demo/lesion_visual.py#L90) and modify it.

**Comment by WHloveHZN** [comment]
Thank you very much

**Comment by wk19990213** [comment]
image
你好，你的显卡显存是多少了，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢

**Comment by wk19990213** [comment]
![image](https://github.com/user-attachments/assets/ceafda2e-3b95-4b76-953c-f53b1d75aaf9)
你好，你的显卡显存是多少了，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢
