### ISSUE TITLE
单GPU测试。batchsize为1。输入测试命令后，程序测试了27张图片后，等待了十几秒，然后被kill掉了，求助

### ISSUE THREAD

**Issue by wk19990213** [CVIU-CSU/M2MRF-Lesion-Segmentation#17]
![image](https://github.com/user-attachments/assets/e75cc4ad-84bf-4da9-9b45-836eccb61b66)

**Comment by haotianll** [comment]
这个可能是 RAM 内存不够导致的

**Comment by wk19990213** [comment]
收到，十分感谢，祝万事顺利



---原始邮件---
发件人: "Haotian ***@***.***&gt;
发送时间: 2024年11月22日(周五) 下午5:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CVIU-CSU/M2MRF-Lesion-Segmentation] 单GPU测试。batchsize为1。输入测试命令后，程序测试了27张图片后，等待了十几秒，然后被kill掉了，求助 (Issue #17)




 
这个可能是 RAM 内存不够导致的
