### ISSUE TITLE
How to train the model without distributed setting?

### ISSUE THREAD

**Issue by o0t1ng0o** [CVIU-CSU/M2MRF-Lesion-Segmentation#2]
Hi @haotianliu001 
Thank you for sharing your code.
I don't want to use the distributed setting. How can I train it with only 1 gpu?

**Comment by haotianll** [comment]
You can simply use a command like `python configs/m2mrf/fcn_hr48-M2MRF-C_40k_idrid_bdice.py`

For more instructions, you can refer to the document [here](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/docs/getting_started.md#train-with-a-single-gpu).

**Comment by o0t1ng0o** [comment]
Thank you very much.

I think your work is very good. 
Is this paper accepted or still under review?

**Comment by haotianll** [comment]
Thank you. It's still under review now. 😺

**Comment by o0t1ng0o** [comment]
Hhhh good luck! 😄

**Comment by haotianll** [comment]
Thank you~
