### ISSUE TITLE
could you please suggest some possible reasons why my testing results are all zero?

### ISSUE THREAD

**Issue by shiqueenTang** [CVIU-CSU/M2MRF-Lesion-Segmentation#6]
I have followed all the readme suggestions, and here are my commands, when I finally managed to get the test file running, somehow the results were wrong, could you please suggest some possible reasons why my testing results are all zero?

running command - python tools/test.py configs/m2mrf/fcn_hr48-M2MRF-A_60k_ddr_bdice.py ./M2MRF-Lesion-Segmentation-master/fcn_hr48-M2MRF-A_60k_ddr_bdice_iter_60000.pth --eval mIoU --show-dir ./M2MRF-Lesion-Segmentation-master/

<img width="871" alt="image" src="https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/96712710/7a1bd59a-7a88-421d-8fd2-f44abb878b33">

**Comment by cdn940912** [comment]
hello, do you know the reasno why? i meet the same problem
![image](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/65482273/ca5b401b-5f6e-47ab-b950-c3a807cb4fe2)
