### ISSUE TITLE
questions about data in training

### ISSUE THREAD

**Issue by aqaaqaaqa** [CVIU-CSU/M2MRF-Lesion-Segmentation#7]
I want to know if all the different types of disease in DDR datasets would be used or just one type of disease in once training process.

**Comment by haotianll** [comment]
Hi, we trained four types of disease with one model at the same time for all experiments.

**Comment by aqaaqaaqa** [comment]
Thanks. Did you combine four types of disease labels in one image? And people who like CLANNAD are very, very GREAT people.

**Comment by haotianll** [comment]
Yes, and you could find the preprocessing code [here](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/tools/prepare_labels.py). Thank you, CLANNAD is a fantastic anime!

**Comment by aqaaqaaqa** [comment]
Thank you! Forgive my poor code ability. Wish you can have a happy life!

**Comment by haotianll** [comment]
You are welcome~
