### ISSUE TITLE
could you please suggest some possible reasons why my testing results are all zero? Looking forward to your reply

### ISSUE THREAD

**Issue by cdn940912** [CVIU-CSU/M2MRF-Lesion-Segmentation#8]
I have followed all the readme suggestions, and here are my commands, when I finally managed to get the test file running, somehow the results were wrong, could you please suggest some possible reasons why my testing results are all zero?

CUDA_VISIBLE_DEVICWES=7 PORT=12345 ./dist_test.sh ../configs/m2mrf/fcn_hr48-M2MRF-C_40k_idrid_bdice.py ./work_dirs/fcn_hr48-M2MRF-C_40k_idrid_bdice/iter_40000.pth 1 --eval mIoU

![2b25cb617f0907b52acfd5fa43a3c1a](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/65482273/b5dcd2d4-ec93-4071-8f33-d2ccedfe58b7)

**Comment by haotianll** [comment]
Hi, did you follow this [code](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/tools/prepare_labels.py) to create the labels?

**Comment by cdn940912** [comment]
Yes, i maybe know the reason, may labels data type is  .tif,converting it to '.png' might solve the problem as you code show.
 To further validate the data, could you please transfer it to my email(869805617@qq.com)? 
Anywhere, Thank you for your assistance ~
![image](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/65482273/9b806840-0c9b-463e-9cb6-af2544117b1a)

**Comment by wk19990213** [comment]
你好，你的显卡显存是多少了
![1732188130071](https://github.com/user-attachments/assets/dd809d16-013c-4421-b236-7153110a87e0)
，我在输入测试指令运行后，系统会把进程kill掉，你遇到过这样的问题吗，非常感谢
